### ISSUE TITLE
ibflex can't parse: KeyError

### ISSUE THREAD

**Issue by IVNXPTRV** [OSadovy/uabean#5]
Hey, first of all, thanks for your importers! I use them to create my own workflow.

But some issue with ibkr, when i run the code (completely from your package, nothing changed or modified), it shows me a KeyError, which is strange because when i eyeball my xml i can see this attribute in  my `<Trade Attributes />`

I tried install ibflex via PyPi and directly from GitHub. Any ideas how can i fix that?

```
* /Users/ivanpetrov/GitHub/cpu/IVN/tests/test.xml ...  ERROR
  Exception in importer code.
  Traceback (most recent call last):
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 115, in parse_data_element
      attrs = dict(
              ^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 116, in <genexpr>
      parse_element_attr(Class, k, v)
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 156, in parse_element_attr
      Type = Class.__annotations__[name]
             ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  KeyError: 'issuerCountryCode'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/beangulp/__init__.py", line 86, in _extract
      entries = extract.extract_from_file(importer, filename, existing_entries)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/beangulp/extract.py", line 40, in extract_from_file
      entries = importer.extract(filename, existing_entries)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/uabean/importers/ibkr.py", line 105, in extract
      statement = parser.parse(open(filename))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 53, in parse
      parsed = parse_element(root)
               ^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 85, in parse_element
      return parse_data_element(elem)
             ^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 125, in parse_data_element
      contained_elements = {child.tag: parse_element(child) for child in elem}
                                       ^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 80, in parse_element
      return parse_element_container(elem)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 101, in parse_element_container
      instances = tuple(parse_data_element(child) for child in elem)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 101, in <genexpr>
      instances = tuple(parse_data_element(child) for child in elem)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 125, in parse_data_element
      contained_elements = {child.tag: parse_element(child) for child in elem}
                                       ^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 83, in parse_element
      return parse_element_container(elem)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 101, in parse_element_container
      instances = tuple(parse_data_element(child) for child in elem)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 101, in <genexpr>
      instances = tuple(parse_data_element(child) for child in elem)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/ivanpetrov/GitHub/cpu/venv/lib/python3.12/site-packages/ibflex/parser.py", line 121, in parse_data_element
      raise FlexParserError(msg)
  ibflex.parser.FlexParserError: Trade has no attribute 'issuerCountryCode'
```

**Comment by IVNXPTRV** [comment]
Well, i found solution: just delete unsupported keys from Flex report settings in my ibkr profile, never mind :)
